Vagrant.configure("2") do |config|
  
  config.vm.define "Ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.provision "shell", "path": "confluence_install.sh"
    ubuntu.vm.provision "shell", "path": "mysql_install.sh"
    ubuntu.vm.network "forwarded_port", guest: 8080, host: 8080
    ubuntu.vm.network "forwarded_port", guest: 3306, host: 3306
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
  
end
